### ISSUE TITLE
This kernel is leaking cum 

### ISSUE THREAD

**Issue by PeroSar** [MrRob0-X/exynos7885-a30s#3]
come back to telegram wen

**Comment by PeroSar** [comment]
Solved in #2
Bai

**Comment by cyberknight777** [comment]
lmaoooooo

**Comment by cyberknight777** [comment]
btw this will be included in github contributions

**Comment by PeroSar** [comment]
> btw this will be included in github contributions

F

**Comment by PeroSar** [comment]
@MrRob0-X is sharma u???
